language: python
python:
- '3.6'
before_install:
- sudo apt-get -y install upx
script:
- "./scripts/workflow.sh test"
- "./scripts/workflow.sh build"
deploy:
  provider: releases
  api_key:
    secure: Jmnpmd861NpWt4ZOfCsB02c9Hd88ioMs4HsvzE+J6cR8d7VHu+iRdtOyNO114VPORXTkFpv8YaFyx/nRdGq/Zpg7G2b8692AlaLdQweQ9NOmCrQLTkK57WaXvPsP6QKXFcMFQDCx90xi+bg9AEryvGjsgQoESQ5Y3ppx6Dwcv20qf+ntw2hRgDjw9EuCQcyVH1fNX1q4RNRPR/2Ukv91G23Au9/Rwrmhfb/quNoHIbu9dzjKXwPJ5ur+1TlGLspjJPkvSe0v0vHOSNTq2Tf2iGaDWerBVIDsxRE20leyJyq6Iq5tX39Lc3+TP/AXgE2wKZGg/12+Bv7OK+orT7N1RO0MEIWUbOPMv62WBwpjzgUvU7WD8yg688zESVUkSgT/4XyHCJX+t528RaWAS/+0w12G8OUK0jBTvr8RSsbn57Y2WrWVy4893NSxsxbK1Z02LTklY/N4VmXcP8hpiogTacBjx3aQBuRG6LxusJU3G5IGwqRmlVQdyV0rh0iSvi9rJbdgZ4mYsVHIvYhoq/fxY9jHCjPzr35goT3ZlwcBpCwW+oum8TkpeNxX0/z/mvM/8o7uAX5thlXfrRh87gTGA+IhoAUHK2NK1xvBhb9KDE3JIx+CAi5L50CLnBbO1f4iWnjCpDtCvNkCXFbhLwf7g1brGEOUmhmvH4ArmT+YjYg=
  file: dist/temply
  on:
    repo: amannocci/temply
  skip_cleanup: 'true'
